name: Terraform Lint
description: "Runs a Terraform Lint"
inputs:
  tf-version:
    required: true
    description: "The version of Terraform to run"

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.tf-version }}
        terraform_wrapper: false

    - name: ✅ Check Formatting
      shell: bash
      id: format
      continue-on-error: true
      run: |
        set +e
        terraform fmt -check -recursive
        echo "exitcode=$?" >> $GITHUB_OUTPUT

    - name: 🛠️ Terraform Format
      shell: bash
      if: ${{ steps.format.outputs.exitcode != 0 }}
      run: |
        terraform fmt -recursive
        echo 'Format Completed ✅' >> $GITHUB_STEP_SUMMARY

    - name: ✅ Add & Commit
      shell: bash
      if: ${{ steps.format.outputs.exitcode != 0 }}
      continue-on-error: true
      run: |
        git config --global user.name '${{ github.actor  }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
        git add -A && git commit -m '[GHA] - Formatted by GitHub Action - Run ${{ github.run_id }}'
        git push
        echo 'Formatting Changes Committed ✅' >> $GITHUB_STEP_SUMMARY
