name: Build and Test
description: Build and Test a Service

inputs:
  service-repository:
    description: The repository for the Service
    required: true
  service-branch:
    description: The branch to test
    required: true

runs:
  using: composite
  steps:
    - name: 📥 Get Codebase
      uses: actions/checkout@v4
      with:
        repository: dvsa/cvs-devops
        ref: ${{ inputs.service-branch }}

    - name: Trigger Build
      uses: ./github/workflows/develop-tag-deploy.yaml
      with:
        service-branch: ${{ inputs.service-branch }}
        service-repository: ${{ inputs.service-repository }}