# For more information, see:
# https://github.com/actions/labeler

# Add 'actions' label when any files inside `.github/workflows` change
actions:
  - .github/**/*.yaml

# Add 'documentation' label when README.md changes
documentation:
  - README.md

# Add 'terraform' label when tf files are changed
terraform:
 - '*.tf'

# Add 'version-bump' label when tf files are changed
version-bump:
 - .terraform-version

javascript:
 - '*.js'

typescript:
 - '*.ts'

groovy:
  - '*.groovy'