name: Store CVS Service
description: Store CVS Lambda Service Artefacts in S3

inputs:
  service_name:
    description: The CVS Service Name
  environment_name:
    description: The environment name
    required: true
  access_token:
    description: GitHub Access Token
    required: true
  s3_bucket:
    description: S3 Bucket for Service Artefacts
    required: true

runs:
  using: composite
  steps:
    - name: Get Artifact
      uses: actions/download-artifact@v8
      with:
        name: ${{ github.event.repository.name }}-artifacts-${{ github.event.pull_request.number || github.run_id }}
        path: artifacts

    - name: Convert and Upload
      shell: bash
      run: |
        # Gather SHA256 for function artifacts, upload to S3 and create Hash Files
        cd artifacts

        # Get repo name from GitHub context
        REPO_FOLDER_NAME="${GITHUB_REPOSITORY##*/}"

        for file in *.zip; do
          SERVICE_NAME=$(echo "$file" | rev | cut -d'-' -f3- | rev)

          LAMBDA_SHA=$(openssl dgst -sha256 -binary "$file" | openssl enc -base64)

          echo "Uploading ${file} to s3://${{ inputs.s3_bucket }}/${REPO_FOLDER_NAME}/${SERVICE_NAME}/"

          echo -n "${{ github.sha }}" | aws s3 cp - \
            "s3://${{ inputs.s3_bucket }}/${REPO_FOLDER_NAME}/${SERVICE_NAME}/latestHash_${{ inputs.environment_name }}.txt" \
            --content-type "text/plain"

          aws s3 cp "$file" \
            "s3://${{ inputs.s3_bucket }}/${REPO_FOLDER_NAME}/${SERVICE_NAME}/${{ github.sha }}.zip" \
            --metadata "sha256sum=${LAMBDA_SHA},Tag=${{ inputs.service_name }},commit=${{ github.sha }}"
        done