name: Terraform Plan
description: Perform a Terraform Plan

inputs:
  options:
    description: Additional Terraform Options 
  validate:
    description: Run a validation on the Terraform first
    default: 'true'
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  environment-type: 
    description: Type of environment (if required)
    required: false
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  plan-retention:
    description: Number of days to retain the plan
    default: '5'
  create-workspace:
    description: Should a new Terraform Workspace be created
    default: 'true'
  repository:
    description: The name of the repository
    default: 'cvs-tf'
  encryption-key:
    description: ARN of a KMS Key to use for Encryption
    required: false
  infracost-key:
    description: API Key for InfraCost
  tfvars:
    description: Should a TFVARS file be used
    default: 'false'
  backend:
    description: Use a custom Backend Configuration
    default: 'false'
  working-directory:
    description: If the Terraform is not in the root of the folder, provide the working working directory
    required: false
  artifact-name:
    description: Name to use for the Terraform Plan Artifact
    default: plan

outputs:
  changes-detected:
    description: Terraform has detected changes
    value: ${{ steps.plan.outputs.changes-detected }}
  validate-outcome:
    description: Outcome of terraform validate
    value: ${{ steps.validate.outcome }}
  plan-outcome:
    description: Outcome of terraform plan
    value: ${{ steps.plan.outcome }}

runs:
  using: composite
  steps:
    - name: Initialize Terraform
      uses: dvsa/cvs-github-actions/terraform-initialize@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: ${{ inputs.create-workspace }}
        working-directory: ${{ inputs.working-directory }}
        backend: ${{ inputs.backend }}

    - name: ✅ Terraform Validate
      id: validate
      shell: bash
      if: ${{ inputs.validate == 'true' }}
      run: |
        terraform validate -no-color | tee validate.txt
        echo 'Terraform Validated ✅' >> $GITHUB_STEP_SUMMARY

    - name: 🛠️ Terraform Plan
      id: plan
      shell: bash
      run: |
        # Create Terraform Plan File
        ${{ inputs.working-directory != '' && format('cd {0}', inputs.working-directory) || '' }}
        terraform plan ${{ inputs.options }} ${{ inputs.tfvars == 'true' && format(' -var-file=environments/{0}.tfvars', case(inputs.environment-type != '', inputs.environment-type, inputs.environment-name)) || '' }} -out terraform.tfplan
        terraform show terraform.tfplan -no-color > plan.txt
        echo 'Plan Completed ✅' >> $GITHUB_STEP_SUMMARY
        plan_detail=$(terraform show -no-color terraform.tfplan | grep -E 'Plan:|Your infrastructure' || echo "No environment currently deployed")
        echo "${plan_detail}" >> $GITHUB_STEP_SUMMARY

        if [[ $(awk '{print index($0, "Plan:")}' <<< $plan_detail) > 0 ]]; then
          # Changes have been detected
          echo "changes-detected=true" >> $GITHUB_OUTPUT
        else
          echo "changes-detected=false" >> $GITHUB_OUTPUT
        fi

    - name: Encrypt Plan File
      uses: dvsa/cvs-github-actions/aws-encrypt@develop
      if: ${{ inputs.encryption-key != '' }}
      with:
        action: encrypt
        encryption-key: ${{ inputs.encryption-key }}
        file: ${{ format('{0}/terraform.tfplan', inputs.working-directory != '' && inputs.working-directory || '.') }} 

    - name: 📝 Upload Plan
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.artifact-name }}-${{ github.run_id }}
        path: |
          ${{ format('{0}/terraform.tfplan{1}', inputs.working-directory != '' && inputs.working-directory || '.', inputs.encryption-key != '' && '.encrypted' || '') }} 
        retention-days: ${{ inputs.plan-retention }}

    # Run Infracost to get idea of cost changes
    - name: 💰 Setup Infracost
      uses: infracost/actions/setup@v3
      id: infracost
      continue-on-error: true
      with:
        api-key: ${{ inputs.infracost-key }}

    - name: 💸 Generate Infracost Information
      shell: bash
      if: ${{ !steps.infracost.outcome == 'failure' }}
      run: |
        # Generate Infracost Information
        ${{ inputs.working-directory != '' && format('cd {0}', inputs.working-directory) || '' }}
        terraform show -json terraform.tfplan > plan.json
        infracost breakdown --path plan.json --format json --out-file breakdown.json
        infracost output --path breakdown.json --format github-comment >> $GITHUB_STEP_SUMMARY
