name: Terraform Apply
description: Perform a Terraform Plan

inputs:
  options:
    description: Additional Terraform Options 
  plan-id:
    description: Artifact Id for a Terraform Plan
    default: plan-${{ github.run_id }}
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.3.9)
    default: 1.3.9
  create-workspace:
    description: Should a new Terraform Workspace be created
    default: 'true'

runs:
  using: composite
  steps:

    - name: Check Initialization
      id: tf
      shell: bash
      run: |
        # Check if Terraform has been Initialized
        [[ -f ".terraform.lock.hcl" ]] && echo "initialized=true" >> $GITHUB_OUTPUT || echo "initialized=false" >> $GITHUB_OUTPUT

    - name: Initialize Terraform
      uses: dvsa/cvs-github-actions/terraform-initialize@feature/CB2-10415
      if: ${{ steps.tf.outputs.initialized == 'false' }}
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: ${{ inputs.create-workspace }}

    - name: ⬇️ Retrieve Plan
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.plan-id }}

    - name: 🛠️ Terraform Apply
      shell: bash
      run: |
        terraform apply ${{ inputs.options }} -lock-timeout=300s terraform.tfplan && \
        echo 'Terraform Applied ✅' >> $GITHUB_STEP_SUMMARY || \
        echo 'Terraform Apply Failed ❌' >> $GITHUB_STEP_SUMMARY
