name: Terraform Apply
description: Perform a Terraform Plan

inputs:
  options:
    description: Additional Terraform Options 
  run-id:
    description: Run Id for a Terraform Plan Artifact
    default: ${{ github.run_id }}
  artifact-name:
    description: Name of the Terraform Plan Artifact
    default: plan
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  create-workspace:
    description: Should a new Terraform Workspace be created
    default: 'true'
  repository:
    description: The name of the repository
    default: 'cvs-tf'
  encryption-key:
    description: ARN of a KMS Key to use for Encryption
    required: false
  tfvars:
    description: Should a TFVARS file be used
    default: 'false'
  backend:
    description: Use a custom Backend Configuration
    default: 'false'
  working-directory:
    description: If the Terraform is not in the root of the folder, provide the working working directory
    required: false

runs:
  using: composite
  steps:
    - name: Initialize Terraform
      uses: dvsa/cvs-github-actions/terraform-initialize@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: ${{ inputs.create-workspace }}
        backend: ${{ inputs.backend }}
        working-directory: ${{ inputs.working-directory }}

    - name: Retrieve Plan
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.artifact-name }}-${{ inputs.run-id }}
        path: ${{ inputs.working-directory }}

    - name: Decrypt Plan File
      uses: dvsa/cvs-github-actions/aws-encrypt@develop
      if: ${{ inputs.encryption-key != '' }}
      with:
        action: decrypt
        encryption-key: ${{ inputs.encryption-key }}
        file: ${{ format('{0}/terraform.tfplan', inputs.working-directory != '' && inputs.working-directory || '.') }} 

    - name: Terraform Apply
      shell: bash
      run: |
        # Apply Terraform from a Plan
        ${{ inputs.working-directory != '' && format('cd {0}', inputs.working-directory) || '' }}
        terraform apply ${{ inputs.options }} terraform.tfplan
        echo 'Terraform Applied ✅' >> $GITHUB_STEP_SUMMARY

