name: Terraform Apply
description: Perform a Terraform Plan

inputs:
  options:
    description: Additional Terraform Options 
  plan-id:
    description: Artifact Id for a Terraform Plan
    default: plan-${{ github.run_id }}
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  environment-type:
    description: Environment Type (e.g. `develop`, `feature`)
    required: false
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  create-workspace:
    description: Should a new Terraform Workspace be created
    default: 'true'
  var-file:
    description: Load an environment specific TFVARS file
    default: 'false'

runs:
  using: composite
  steps:
    - name: Initialize Terraform
      uses: dvsa/cvs-github-actions/terraform-initialize@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: ${{ inputs.create-workspace }}

    - name: Retrieve Plan
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.plan-id }}

    - name: Terraform Apply
      shell: bash
      run: |
        # Apply Terraform from a Plan
        terraform apply ${{ inputs.options }} ${{ inputs.var-file == 'true' && format('-var-file="environments/{0}.tfvars"', inputs.environment-type) || '' }} -lock-timeout=300s terraform.tfplan && \
        echo 'Terraform Applied ✅' >> $GITHUB_STEP_SUMMARY || \
        echo 'Terraform Apply Failed ❌' >> $GITHUB_STEP_SUMMARY
