name: Drop MySQL Schema
description: Drop a Schema in MySQL

inputs:
  environment-name:
    description: Environment Identifier (e.g. cb2-`1099`)
    required: true
  environment-type:
    description: Environment Type (e.g. `feature`, `develop` etc)
    required: true
  schema:
    description: Base Schema to drop (e.g. `CVSNOP`)
    required: true
  dry-run:
    description: Don't perform destruction, just output information
    default: "true"

runs:
  using: composite
  steps:
    - name: ðŸ›¢ï¸ Remove Schemas
      id: remove_schemas
      shell: bash
      run: |
        # Drop the requested Schema

        if [ "${{ inputs.environment-type }}" == "feature" ]; then
          schema="${{ inputs.schema }}$(echo ${{ inputs.environment-name }} | tr '[:lower:]' '[:upper:]' | tr -d '-')"
        else
          schema=${{ inputs.schema }}
        fi

        aws secretsmanager get-secret-value --secret-id ${{ inputs.environment-type }}/mysql/config --query SecretString --region=eu-west-1 --output text > my.cnf
        if [ "${{ inputs.dry-run }}" == 'false' ]; then 
          sudo /etc/init.d/mysql start
          mysql --defaults-file=my.cnf -e "DROP SCHEMA IF EXISTS ${schema}"
        else
          echo mysql --defaults-file=my.cnf -e "DROP SCHEMA IF EXISTS ${schema}"
        fi

