name: DynamoDB Table Purge
description: Delete all items from a DynamoDB Table

inputs:
  table:
    description: The DynamoDB Table ID to be purged
    required: true
  partition-key-name:
    description: The partition key name of the table
    required: true
  sort-key-name:
    description: The sort key name of the table (optional)
    required: false
  dry-run:
    description: Don't perform action, just output information
    default: "true"

runs:
  using: composite
  steps:
    - name: Check jq installation
      shell: bash
      run: |
        if ! command -v jq &> /dev/null
        then
          echo "jq could not be found, installing..."
          sudo apt-get update
          sudo apt-get install -y jq
        fi

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' 

    - name: Install dependencies
      run: npm install 
      working-directory: ./table-purge 

    - name: Purge Table
      shell: bash
      run: |
        echo "Running purge script..."
        node index.js \
          --table "${{ inputs.table }}" \
          --partition-key-name "${{ inputs['partition-key-name'] }}" \
          --partition-key-value "${{ inputs['partition-key-value'] }}" \
          --sort-key-name "${{ inputs['sort-key-name'] }}" \
          --dry-run "${{ inputs.dry-run }}"

    - name: Dry run message
      shell: bash
      if: ${{ inputs.dry-run == 'true' }}
      run: echo "Dry run complete. No items were deleted."
