name: DynamoDB Table Purge
description: Delete all items from a DynamoDB Table

inputs:
  table:
    description: The DynamoDB Table ID to be purged
    required: true
outputs:
  table-id:
    description: Calculated ID for the table
    value: ${{ steps.purge_table.outputs.table_id }}

runs:
  using: composite
  steps:

    - name: Purge Table
      id: purge_table
      shell: bash
      run: |
        # Empty the DynamoDB Tables

        # Get Range and Hash Key from Table
        table_id=$(aws dynamodb list-tables | jq -r '.TableNames[] | select(. | contains("${{ inputs.table }}"))')
        hash_key=$(aws dynamodb describe-table --table-name ${table_id} --query 'Table.KeySchema[?KeyType==`HASH`].AttributeName | [0]' | tr -d '"')
        range_key=$(aws dynamodb describe-table --table-name ${table_id} --query 'Table.KeySchema[?KeyType==`RANGE`].AttributeName | [0]' | tr -d '"')
        [[ "${range_key}" != null ]] && range_key=''

        echo "--attributes-to-get ${hash_key} ${range_key}"
        # Scan Table and remove each Item
        aws dynamodb scan --attributes-to-get ${hash_key} ${range_key} --table-name ${table_id} --query 'Items[*]' \
          | jq --compact-output '.[]' \
          | tr ',' '\n' \
          | xargs -0 \
          echo aws dynamodb delete-item --table-name ${table_id} --key {}

        # Send Table ID out for seed job (if required)
        echo "table_id=${table_id}" >> $GITHUB_OUTPUT



     