name: DynamoDB Table Purge
description: Delete all items from a DynamoDB Table

inputs:
  table:
    description: The DynamoDB Table ID to be purged
    required: true
  dry-run:
    description: Don't perform action, just output information
    default: "true"

runs:
  using: composite
  steps:

    - name: Purge Table
      shell: bash
      run: |
        # Empty the DynamoDB Tables

        # Get Range and Hash Key from Table
        hash_key=$(aws dynamodb describe-table --table-name ${{ inputs.table }} --query 'Table.KeySchema[?KeyType==`HASH`].AttributeName | [0]' | jq -r)
        range_key=$(aws dynamodb describe-table --table-name ${{ inputs.table }} --query 'Table.KeySchema[?KeyType==`RANGE`].AttributeName | [0]' | jq -r)
        [[ $range_key == null ]] && range_key=''

        # Scan Table and remove each Item
        IFS=$'\n'
        for item in $(aws dynamodb scan --attributes-to-get ${hash_key} ${range_key} --table-name ${{ inputs.table }} --query 'Items[*]' | jq -c '.[]' | uniq); do
          echo "Purging $item"
          ${{ inputs.dry-run == 'true' && 'echo ' || '' }}aws dynamodb delete-item --table-name ${{ inputs.table }} --key $item
        done



     