name: DynamoDB Table Purge
description: Delete all items from a DynamoDB Table

inputs:
  table:
    description: The DynamoDB Table ID to be purged
    required: true

runs:
  using: composite
  steps:

    - name: Purge Table
      shell: bash
      run: |
        # Empty the DynamoDB Tables

        # Get Range and Hash Key from Table
        hash_key=$(aws dynamodb describe-table --table-name ${{ inputs.table }} --query 'Table.KeySchema[?KeyType==`HASH`].AttributeName | [0]' | tr -d '"')
        range_key=$(aws dynamodb describe-table --table-name ${{ inputs.table }} --query 'Table.KeySchema[?KeyType==`RANGE`].AttributeName | [0]' | tr -d '"')
        [[ "${range_key}" != null ]] && range_key=''

        echo "--attributes-to-get ${hash_key} ${range_key}"
        # Scan Table and remove each Item
        itemKeys=$(aws dynamodb scan --attributes-to-get ${hash_key} ${range_key} --table-name ${{ inputs.table }} --query 'Items[*]' \
          | jq --compact-output '.[]' \
          | tr ',' '\n')
        for itemKey in $itemKeys; do
          echo Deleting itemKey from ${{ inputs.table }} 
          aws dynamodb delete-item --table-name ${{ inputs.table }} --key itemKey
        done



     