name: DynamoDB Table Purge
description: Delete all items from a DynamoDB Table

inputs:
  table:
    description: The DynamoDB Table ID to be purged
    required: true
  dry-run:
    description: Don't perform action, just output information
    default: "true"

runs:
  using: node20
  main: index.js
  