name: Terraform Plan
description: "Runs a Terraform Plan"
inputs:
  tf-version:
    required: true
    description: "The version of Terraform to run"
  aws-role-to-assume:
    required: false
    description: "The AWS Role to assume"
  workspace:
    required: false
    description: "The Terraform workspace to action against"
  retention-days:
    required: false
    default: '3'
    description: "The amount of days to hold a plan artefact for"

runs:
  using: composite
  steps:
    - shell: bash
      run: pip3 install ansi2html

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: eu-west-1
        role-session-name: Terraform-GHA

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.tf-version }}
        terraform_wrapper: false

    - name: 🛠️ Terraform Init
      shell: bash
      run: |
        terraform init -lock-timeout=300s
        terraform workspace select ${{ inputs.workspace }}

    - name: ✅ Terraform Validate
      shell: bash
      run: |
        terraform validate -no-color

    - name: 🛠️ Terraform Plan
      shell: bash
      continue-on-error: true
      run: |
        terraform plan -out terraform.tfplan
        terraform show terraform.tfplan -no-color | ansi2html > plan.html

    - name: 📝 Upload Plan
      uses: actions/upload-artifact@v3
      with:
        name: plan-${{ github.run_id }}
        path: plan.html
        retention-days: ${{ inputs.retention-days }}
