name: Terraform Scan
description: Perform a Terraform Scan

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  create-workspace:
    description: Should a new Terraform Workspace be created
    default: 'false'
  backend:
    description: Use a custom Backend Configuration
    default: 'false'
  working-directory:
    description: If the Terraform is not in the root of the folder, provide the working working directory
    required: false

outputs:
  init-outcome:
    description: Outcome of terraform init
    value: ${{ steps.init.outcome }}
  fmt-outcome:
    description: "Outcome of terraform format"
    value: ${{ steps.fmt.outcome }}
  checkov-outcome:
    description: "Outcome of checkov scan"
    value: ${{ steps.checkov.outcome }}

runs:
  using: composite
  steps:

    - name: Initialize Terraform
      id: init
      uses: dvsa/cvs-github-actions/terraform-initialize@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: ${{ inputs.create-workspace }}
        working-directory: ${{ inputs.working-directory }}
        backend: ${{ inputs.backend }}
    
    - name: Terraform format
      id: fmt
      continue-on-error: true
      shell: bash
      run: |
        terraform fmt -check=true -diff=true | tee fmt.txt || true
      
    - name: Checkov Scan
      id: checkov
      continue-on-error: true
      run: |
        # Checkov Scan
        ${{ inputs.working-directory != '' && format('cd {0}', inputs.working-directory) || '' }}
        checkov -d . --skip-framework github_actions -o github_failed_only  --output-file-path checkov-report-${{ github.run_id }}.md
      shell: bash

    - name: 📝 Upload Report
      uses: actions/upload-artifact@v7
      with:
        name: checkov-report-${{ github.run_id }}
        path: checkov-report-${{ github.run_id }}.md
        retention-days: 5
