name: Terraform Scan
description: Perform a Terraform Scan

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  create-workspace:
    description: Should a new Terraform Workspace be created
    default: 'false'

runs:
  using: composite
  steps:

    - name: Initialize Terraform
      uses: dvsa/cvs-github-actions/terraform-initialize@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: ${{ inputs.create-workspace }}
    
    - name: Terraform format
      continue-on-error: true
      shell: bash
      run: |
        terraform fmt -check=true -diff=true || true
      
    - name: Chekov Scan
      run: |
        brew install checkov

        checkov -d . --skip-framework github_actions --output sarif > checkov_results.sarif ||  error_code=$?
        
        if [[ $error_code -ne 0 ]]; then
          echo "Checkov scan failed" >> $GITHUB_STEP_SUMMARY
        else
          echo "Checkov scan passed" >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: checkov_results.sarif


    - name: Terraform Lint 
      shell: bash
      run: |
        tflint --init
        tflint