name: Terraform Scan
description: Perform a Terraform Scan

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  create-workspace:
    description: Should a new Terraform Workspace be created
    default: 'false'

runs:
  using: composite
  steps:

    - name: Initialize Terraform
      uses: dvsa/cvs-github-actions/terraform-initialize@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: ${{ inputs.create-workspace }}
    
    - name: Terraform format
      continue-on-error: true
      shell: bash
      run: |
        terraform fmt -check=true -diff=true || true
      
    - name: Chekov Scan
      continue-on-error: true 
      run: |
        brew install checkov
        checkov -d . --skip-framework github_actions -o github_failed_only --output-file-path checkov_failures.json >> GITHUB_STEP_SUMMARY
      shell: bash

      # retention for 5 days 

    # - name: Upload SARIF results
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: checkov_results.sarif