name: Dynamo Export
description: Export a DynamoDB Table to S3

inputs:
  environment:
    description: The Environment that the Table lives in
    required: true
  dynamo-table:
    description: The DynamoDB Table name to be Exported
    required: true
  enable-backups:
    description: Should Backups be enabled once complete
    default: "true"

runs:
  using: composite
  steps:

    - name: Export Table
      shell: bash
      env:
        s3-bucket: cvs-${{ inputs.environment }}-tf-data
        s3-key: dynamodb-extract
      run: |
        # Create Table Backup
        account=$(aws sts get-caller-identity --query "Account" --output text)
        aws dynamodb update-continuous-backups --table-name "${{ inputs.dynamo-table }}" --point-in-time-recovery-specification PointInTimeRecoveryEnabled=True
        aws dynamodb export-table-to-point-in-time --table-arn "arn:aws:dynamodb:eu-west-1:${account}:table/${{ inputs.dynamo-table }}" --s3-bucket ${{ env.s3-bucket }} --s3-prefix ${{ env.s3-key }}/${{ inputs.dynamo-table }}/$(date '+%-m')/$(date '+%-d') --export-format DYNAMODB_JSON --s3-sse-algorithm AES256
        aws dynamodb update-continuous-backups --table-name "${{ inputs.dynamo-table }}" --point-in-time-recovery-specification PointInTimeRecoveryEnabled=${{ inputs.enable-backups }}
        