name: Get Stale Branch Lists
description: Identifies stale branches in Github

inputs:
  repositories:
    description: The repositories to scan
    required: true
  workspaces:
    description: Terraform Workspaces currently active
    required: true
  branch_age:
    description: Min age (days) to accept as "Old"
    default: 365
env:
  PYTHONUNBUFFERED: 1
runs:
  using: composite
  steps:

    - name: Link requirements
      shell: bash
      run: |
        # Create local copy of requirements
        ln -s ${{ github.action_path }}/requirements.txt ./requirements.txt
  
    - name: 🐍 Setup Python
      uses: actions/setup-python@v7
      id: stale-branches
      with:
        python-version: '3.13'
        #cache: 'pip'
        #cache-dependency-path: ${{ github.action_path }}/main.py
        #pip-install: -r requirements.txt

    - name: Configure Python Env
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        
    - name: Scan Repositories
      id: jira
      shell: bash
      run: |
        # Cache Jira Tickets by not sending a repository parameter
        source venv/bin/activate
        for repo in $(jq -r '.[]' <<< '${{ inputs.repositories }}'); do
          python ${{ github.action_path }}/main.py $repo
        done

    - name: 🗜️ Merge Branch Lists
      shell: bash
      run: |
        # Collect branch details from all repository files
        # Retain True as dominant value
        # Retain youngest age
        jq -s '
          def merge_value($k; $a; $b):
            if ($a | type) == "object" and ($b | type) == "object" then
              reduce ($a | keys_unsorted[]) as $subk
                ($b;
                if has($subk) then
                  .[$subk] = merge_value($subk; $a[$subk]; $b[$subk])
                else
                  .
                end
                )
            elif ($a | type) == "boolean" and ($b | type) == "boolean" then
              ($a or $b)
            elif $k == "age"
                and ($a | type) == "number"
                and ($b | type) == "number" then
              ([$a, $b] | min)
            else
              $b
            end;

          reduce .[] as $item
            ({};
            reduce ($item | keys_unsorted[]) as $k
              (.;
                if has($k) then
                  .[$k] = merge_value($k; .[$k]; $item[$k])
                else
                  .[$k] = $item[$k]
                end
              )
            )
        ' cvs-*.json > branches.json
    
    - name: 🖥️ Branch Table
      if: ${{ inputs.manual == null }}
      shell: bash
      run: |
        # Output Markdown Table
        jq -r 'def fmt($cell):
          if $cell == true then "✅"
          elif $cell == false then "❌"
          elif $cell == null then "None"
          else ($cell | tostring)
          end;

          (to_entries | sort_by(.key)) as $entries
          | ($entries[0].value | keys_unsorted) as $cols
          | (
            "| branch | \($cols | join(" | ")) |",
            "|---| " + ($cols | map("---") | join(" | ")) + " |",
            (
              $entries[]
              | .value as $v
              | "| " + (
                  [.key]
                  + ($cols | map(fmt($v[.])))
                  | join(" | ")
                ) + " |"
            )
          )
        ' branches.json > branch_list.md
        cat branch_list.md >> $GITHUB_STEP_SUMMARY

    - name: 📋 Generate SubLists
      if: ${{ inputs.manual == null }}
      shell: bash
      run: |
        # Generate SubLists
        mkdir branch_lists

        # Old Branches with a completed pull request over a certain age
        jq '                                      
          to_entries                                                                                                        
          | sort_by(.key)
          | map(select(.value.pull_request == true)) 
          | map(select(.value.age > ${{ inputs.branch_age }}))
          | map(.key)                                                                                       
        ' branches.json > branch_lists/pull_request.json

        # Stale Branches which consist of "Withdrawn" or "No Longer Required" tickets
        # This will not include non-standard branch names
        jq '                                      
          to_entries                                                                                                        
          | sort_by(.key)
          | map(select(.value.stale == true))
          | map(.key)                                                                                       
        ' branches.json > branch_lists/stale.json

        # Branches marked as `Done` with a completed pull request over a certain age
        # This will not include non-standard branch names
        jq '                                      
          to_entries                                                                                                        
          | sort_by(.key)
          | map(select(.value.done == true))
          | map(select(.value.pull_request == true)) 
          | map(select(.value.age > ${{ inputs.branch_age }}))
          | map(.key)                                                                                       
        ' branches.json > branch_lists/done.json

