name: Terraform Apply
description: Apply Terraform

inputs:
  environment:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.3.9)
    default: 1.3.9

runs:
  using: composite
  steps:

    - name: ⚙️ Configure Terraform
      id: terraform_config
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: ⏳ Initialize Terraform
      id: terraform_init
      shell: bash
      run: |
        terraform init
        terraform workspace select ${{ inputs.environment }}
        echo 'Workspace: ${{ inputs.environment }}' >> $GITHUB_STEP_SUMMARY