name: Terraform Initialize
description: Initialize Terraform

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  working-directory: 
    description: The working directory of the code
    required: false
  create-workspace:
    description: Create new Workspace if required
    default: 'true'
  terraform-vars:
    description: Load an environment specific TFVARS file
    default: 'false'

runs:
  using: composite
  steps:
    - name: Configure Terraform
      id: terraform_config
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: Initialize Terraform
      id: terraform_init
      shell: bash
      run: |
        # Initialize ${{ inputs.environment-name }}
        if [[ ! -f ".terraform/environment" ]]; then
          terraform -ch-dir="${{ github.workspace }}/${{ inputs.working-directory }}" init ${{ inputs.terraform-vars == 'true' && format('-var-file="environments/{0}.tfvars"', inputs.environment-type) || '' }}
          terraform workspace select ${{ inputs.create-workspace == 'true' && '-or-create' || '' }} ${{ inputs.environment-name }} \
          && $(echo "Workspace: ${{ inputs.environment-name }}" >> $GITHUB_STEP_SUMMARY)
        fi  
