name: Terraform Initialize
description: Initialize Terraform

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  backend:
    description: Use a custom Backend Configuration
    default: 'false'
  working-directory:
    description: If the Terraform is not in the root of the folder, provide the working working directory
    required: false
  create-workspace:
    description: Create new Workspace if required
    default: 'true'
  region:
    description: AWS Region
    default: 'eu-west-1'

runs:
  using: composite
  steps:
    - name: Configure Terraform
      id: terraform_config
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: Setup GIT
      shell: bash
      run: |
        git init -b temp # Perform a git initialization, so that the git commands work
        gh auth setup-git
        
    - name: Initialize Terraform
      id: terraform_init
      shell: bash
      run: |
        # Initialize ${{ inputs.environment-name }}
        ${{ inputs.working-directory != '' && format('cd {0}', inputs.working-directory) || '' }}

        # Clear any lock files for ${{ inputs.environment-name }}
        bucket=${{ fromJson(inputs.backend) && format('cvs-tf-state-{0}', inputs.region) || 'cvs-tf-environment' }}
        folder=${{ fromJson(inputs.backend) && format('{0}/{1}', env.TF_AWS_ACCOUNT_NAME, inputs.environment-name) || format('env:/{0}', inputs.environment-name) }}

        for lock in $(aws s3api list-objects-v2 --bucket ${bucket} --prefix ${folder} --query "Contents[?ends_with(Key, 'tflock')].Key" --output text); do
          if [[ "${lock}" != "None" ]]; then
            printf "🗑️ \033[0;34mDeleting Lock File \033[0m${lock}\n"
            aws s3api delete-object --bucket ${bucket} --key ${lock}
          fi
        done

        # Initialise Terraform
        if [[ ! -f ".terraform/environment" ]]; then
          terraform init -upgrade${{ fromJson(inputs.backend) && format(' -backend-config="workspace_key_prefix={0}"', env.TF_AWS_ACCOUNT_NAME) || '' }}
          terraform workspace select${{ fromJson(inputs.create-workspace) && ' -or-create' || '' }} ${{ inputs.environment-name }} \
          && $(echo "Workspace: ${{ inputs.environment-name }}" >> $GITHUB_STEP_SUMMARY)
        fi  
 