name: Terraform Initialize
description: Initialize Terraform

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.3.9)
    default: 1.3.9
  create-workspace:
    description: Create new Workspace if required
    default: 'true'

runs:
  using: composite
  steps:

    - name: ⚙️ Configure Terraform
      id: terraform_config
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: ⏳ Initialize Terraform
      id: terraform_init
      shell: bash
      run: |
        # Initialize ${{ inputs.environment-name }}
        create_workspace=$([[ "${{ inputs.create-workspace }}" == 'true' ]] && echo "-or-create" || echo "" )
        terraform init
        terraform workspace select ${{ inputs.environment-name }} ${create_workspace} \
        && $(echo "Workspace: ${{ inputs.environment-name }}" >> $GITHUB_STEP_SUMMARY)

        
