name: Seed all tables
description: Seed all tables

inputs:
  environment-name:
    description: Branch Identifier (either GitHub Branch or Environment Name)
    required: true
  github-branch:
    description: The Github Branch
  repository:
    description: The repository hosting the Seeds

runs:
  using: composite
  steps:

    - name: 📥 Get Codebase
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.github-branch }}

    - name: 📥 Get Seed Tables
      uses: dvsa/${{ inputs.repository }}/.github/workflows/seed-tables.yaml@feature/CB2-10422
      with:
        environment-name: ${{ inputs.environment-name }}
        environment: ${{ inputs.environment }}
    