name: Terraform Destroy
description: Destroy an Environment using Terraform

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  folder-name:
    description: Optional folder name, if not in repository
    default: '.'
  state-account:
    description: Account Name for Core TF Standard
    required: false
  repository:
    description: The name of the repository
    default: 'cvs-tf'
  encryption-key:
    description: ARN of a KMS Key to use for Encryption
    required: false
  infracost-key:
    description: API Key for InfraCost
  dry-run:
    description: Don't perform action, just output information
    default: "true"

runs:
  using: composite
  steps:
    - name: Initialize Terraform
      uses: dvsa/cvs-github-actions/terraform-initialize@develop
      with:
        folder-name: ${{ inputs.folder-name }}
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: 'false'
        state-account: ${{ inputs.state-account }}

    - name: Refresh Terraform
      id: refresh
      uses: dvsa/cvs-github-actions/terraform-refresh@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        repository: ${{ inputs.repository }}
        create-workspace: 'false'
        state-account: ${{ inputs.state-account }}

    - name: Remove VPC Connections
      shell: bash   
      env:
        AWS_PROFILE: main     
      run: |
        # Remove all Lambda VPC Connections
        cd ${{ inputs.folder-name }}
        for lambda in $(terraform show -no-color }${{ inputs.state-account != '' && ' -var-file=environments/$(terraform workspace show).tfvars' || '' }} | grep -E '\s+arn\s+=\s.*:lambda.*' | sed -E 's/.*"(.*:lambda.*:function:[a-z0-9-]+).*"/\1/' | sort | uniq); do
          echo "${{ inputs.dry-run == 'true' && '(dryrun) ' || '' }}remove: ${lambda}"
          ${{ inputs.dry-run == 'true' && 'echo ' || '' }}aws lambda update-function-configuration --function-name ${lambda} --vpc-config '{"SubnetIds":[], "SecurityGroupIds":[]}' >/dev/null
        done

    - name: Terraform Plan
      id: plan
      if: ${{ steps.refresh.outcome == 'success' }}
      uses: dvsa/cvs-github-actions/terraform-plan@develop
      with:
        options: '-destroy'
        validate: 'false'
        environment-name: ${{ inputs.environment-name }}
        terraform-version: ${{ inputs.terraform-version }}
        create-workspace: 'false'
        encryption-key: ${{ inputs.encryption-key }}
        infracost-key: ${{ inputs.infracost-key }}
        folder-name: ${{ inputs.folder-name }}
        state-account: ${{ inputs.state-account }}

    - name: Terraform Apply
      id: apply
      if: ${{ inputs.dry-run == 'false' && steps.refresh.outcome == 'success' && steps.plan.outputs.changes-detected == 'true' }}
      uses: dvsa/cvs-github-actions/terraform-apply@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: 'false'
        encryption-key: ${{ inputs.encryption-key }}
        folder-name: ${{ inputs.folder-name }}
        state-account: ${{ inputs.state-account }}
        
    - name: Remove Workspace
      if: ${{ inputs.dry-run == 'false' && steps.refresh.outcome == 'success' && steps.plan.outputs.outcome == 'success' && steps.apply.outcome == 'success' }}
      shell: bash
      run: |
        # Remove ${{ inputs.environment-name }} Workspace
        cd ${{ inputs.folder-name }}
        terraform workspace select default
        terraform workspace delete ${{ inputs.environment-name }} 
        echo "Terraform Workspace \`${{ inputs.environment-name }}\` Deleted!" >> $GITHUB_STEP_SUMMARY

    - name: Remove Hash Files
      id: remove_hash_files
      uses: dvsa/cvs-github-actions/hash-delete@develop
      with:
        environment-name: ${{ inputs.environment-name }}
        dry-run: ${{ inputs.dry-run }}
