name: Create Branch
description: Create Branch for a given environment

inputs:
  github-branch:
    description: GitHub Branch to delete (e.g. `feature/CB2-1099`)
    required: true
  repository:
    description: GitHub Repository where the Branch will be created
    required: true
  branch-source:
    description: Branch or Tag to create from
    default: 'develop'
  dry-run:
    description: Don't perform action, just output information
    default: 'false'
runs:
  using: composite
  steps:
    - name: Delete Branch (if it exists)
      shell: bash
      run: |
        # Create Branch ${{ inputs.github-branch }}
        gh auth setup-git
        if [[ ! $(awk '{print length}' <<< $(git ls-remote --heads https://github.com/dvsa/${{ inputs.repository }} ${{ inputs.github-branch }})) > 0 ]]; then
          commit_id=$(git ls-remote --tags https://github.com/dvsa/${{ inputs.repository }} ${{ inputs.branch-source }})
          [[ $(awk '{print length($0)}' <<< $commit_id) == 0 ]] && commit_id=$(git ls-remote --heads https://github.com/dvsa/${{ inputs.repository }} develop)
          ${{ inputs.dry-run == 'true' && 'echo' || '' }} gh api -X POST /repos/dvsa/${{ inputs.repository }}/git/refs -f ref='refs/heads/${{ inputs.github-branch }}' -f sha="$(sed -E 's/\t+.*//g' <<< ${commit_id})"
          echo "✅ Created Branch ${{ inputs.github-branch }}" >> $GITHUB_STEP_SUMMARY
        fi
