name: Terraform Apply
description: "Runs a Terraform Apply"
inputs:
  tf-version:
    required: true
    description: "The version of Terraform to run"
  aws-role-to-assume:
    required: false
    description: "The AWS Role to assume"
  workspace:
    required: false
    description: "The Terraform workspace to action against"

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: eu-west-1
        role-session-name: Terraform-GHA

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.tf-version }}
        terraform_wrapper: false

    - name: 🛠️ Terraform Init
      shell: bash
      run: |
        terraform init -lock-timeout=300s
        terraform workspace select ${{ inputs.workspace }} || terraform workspace new ${{ inputs.workspace }}

    - name: 🛠️ Terraform Apply
      shell: bash
      continue-on-error: true
      run: |
        terraform apply -lock-timeout=300s -no-color -auto-approve
