name: Delete Branch
description: Remove Branch for a given environment

inputs:
  github-branch:
    description: GitHub Branch to delete (e.g. `feature/CB2-1099`)
    required: true
  repository:
    description: GitHub Repository where the Branch will be created
    required: true
  dry-run:
    description: Don't perform action, just output information
    default: 'true'

runs:
  using: composite
  steps:
    - name: Delete Branch (if it exists)
      shell: bash
      run: |
        # Delete Branch ${{ inputs.github-branch }}
        gh auth setup-git
        if [[ $(awk '{print length}' <<< $(git ls-remote --heads https://github.com/dvsa/${{ inputs.repository }} ${{ inputs.github-branch }})) > 0 ]]; then
          gh repo clone dvsa/${{ inputs.repository }} && cd ${{ inputs.repository }}
          ${{ inputs.dry-run == 'true' && 'echo' || '' }} git push -d origin ${{ inputs.github-branch }} --no-verify
          echo "✅ Deleted Branch ${{ inputs.github-branch }}" >> $GITHUB_STEP_SUMMARY
        fi
