name: Terraform refresh
description: Refresh the Terraform State

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  create-workspace:
    description: Create new Workspace if required
    default: 'true'
  folder-name:
    description: Optional folder name, if not in repository
    default: '.'
  state-account:
    description: Account Name for Core TF Standard
    required: false
  repository:
    description: The name of the repository
    default: 'cvs-tf'
    
runs:
  using: composite
  steps:
    - name: Initialize Terraform
      uses: dvsa/cvs-github-actions/terraform-initialize@develop
      with:
        folder-name: ${{ inputs.folder-name }}
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: ${{ inputs.create-workspace }}
        state-account: ${{ inputs.state-account }}

    - name: Refresh Terraform
      id: refresh
      continue-on-error: true
      shell: bash
      env:
        AWS_PROFILE: main
      run: |
        # Refresh Terraform
        cd ${{ inputs.folder-name }}
        terraform refresh ${{ inputs.state-account != '' && ' -var-file=environments/$(terraform workspace show).tfvars' || '' }}

    - name: 🔓 Unlock State File
      if: steps.refresh.outcome == 'failure'
      uses: dvsa/cvs-github-actions/terraform-state-unlock@develop
      with:
        repository: ${{ inputs.repository }}
        environment-name: ${{ inputs.environment-name }}