name: Branch Manager

on:
  repository_dispatch:

jobs:
  create-branch:
    if: ${{ github.event.client_payload.branch-to-create != 'N/A' }}
    uses: ./.github/workflows/manage-branch.yaml
    with:
      source-branch: ${{ github.event.client_payload.source-branch }}
      branch-to-create: ${{ github.event.client_payload.branch-to-create }}

  delete-branch:
    if: ${{ github.event.client_payload.branch-to-delete != 'N/A' }}
    uses: ./.github/workflows/manage-branch.yaml
    with:
      branch-to-delete: ${{ github.event.client_payload.branch-to-delete }}
