name: Branch Manager

on:
  repository_dispatch:

jobs:
  manage-branch:
    uses: ./.github/workflows/manage-branch.yaml
    with:
      create: ${{ github.event.client_payload.action == 'create' }}
      source-branch: ${{ github.event.client_payload.source-branch }}
      delete: ${{ github.event.client_payload.action == 'delete' }}
      branch: ${{ github.event.client_payload.branch }}
