name: Create & Build Job
on: [repository_dispatch]
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'echo "field: ${{ github.event.client_payload.branch-to-create }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'

  build:
    needs: [ create-branch ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'echo "field: ${{ github.event.client_payload.build }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
  
