name: Branch Manager

on:
  repository_dispatch:

jobs:
  create-branch:
    if: ${{ github.event.client_payload.action == 'create' }}
    uses: ./.github/workflows/manage-branch.yaml
    with:
      create: true
      source-branch: ${{ github.event.client_payload.source-branch }}
      branch-to-create: ${{ github.event.client_payload.branch-to-create }}

  delete-branch:
    if: ${{ github.event.client_payload.action == 'delete' }}
    uses: ./.github/workflows/manage-branch.yaml
    with:
      delete: true
      branch-to-delete: ${{ github.event.client_payload.branch-to-delete }}
