name: Manage Branch 🎋

on:
  repository_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  manage-branch:
    uses: ./.github/workflows/crt-bld-dlt.yaml
    with:
      action: ${{ github.event.client_payload.action }}
      branch: ${{ github.event.client_payload.branch }}
      source-branch: ${{ github.event.client_payload.source-branch }}
