name: Manage Branch 🎋

on:
  repository_dispatch:

permissions:
  contents: write
  id-token: write

env:
  SOURCE: ${{ github.event.client_payload.source-branch }}
  BRANCH: ${{ github.event.client_payload.branch }}

jobs:
  create:
    if: ${{ fromJSON(github.event.client_payload.action == 'create') }}
    name: Create $BRANCH from $SOURCE
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout $SOURCE
        uses: actions/checkout@v3
        with:
          ref: $SOURCE

  delete:
    if: ${{ github.event.client_payload.action == 'delete' }}
    name: Delete $BRANCH
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout Develop
        uses: actions/checkout@v3
        with:
          ref: 'develop'