name: Manage Branch 🎋

on:
  repository_dispatch:

permissions:
  contents: write
  id-token: write

env:
  SOURCE: ${{ github.event.client_payload.source-branch }}
  BRANCH: ${{ github.event.client_payload.branch }}

jobs:
  create:
    if: ${{ fromJSON(github.event.client_payload.action == 'create') }}
    name: Create ${{github.event.client_payload.branch}} from ${{github.event.client_payload.source-branch}}
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout ${{ env.SOURCE }}
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SOURCE }}

  delete:
    if: ${{ github.event.client_payload.action == 'delete' }}
    name: Delete ${{github.event.client_payload.branch}}
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout Develop
        uses: actions/checkout@v3
        with:
          ref: 'develop'