name: Manage Branch

on: 
  workflow_call:
    inputs:
      create:
        type: boolean
        default: false
      delete:
        type: boolean
        default: false
      source-branch:
        type: string
        default: develop
      branch:
        type: string
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  create:
    if: ${{ fromJSON(inputs.create) }}
    name: Create ${{ inputs.branch }} from ${{ inputs.source-branch }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout ${{ inputs.source-branch }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.source-branch }}
      

  delete:
    if: ${{ fromJSON(inputs.delete) }}
    name: Delete ${{ inputs.branch }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout Develop
        uses: actions/checkout@v3
        with:
          ref: 'develop'
