name: Node JS CI

on:
  workflow_call:
    # secrets:
    #   CVS_ACCESS_TOKEN:
    #     required: false

jobs:
  node-ci:
    runs-on: ubuntu-latest
    # env:
    #   CVS_ACCESS_TOKEN: ${{ secrets.CVS_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Confirm Node and NPM versions
        run: |
          node -v
          npm -v

      # - name: Create .npmrc
      #   run: echo "//npm.pkg.github.com/:_authToken=$CVS_ACCESS_TOKEN" >> ~/.npmrc

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Security Check
        run: echo 'Skipping for now'

      - name: Configure Tools
        run: npm run tools-setup

      - name: Run linting
        run: npm run lint

      - name: Build
        run: npm run build      
        
      - name: Run Tests
        run: npm run test

      - name: Run Integration Tests
        run: npm run test-i

      - name: Sonar Scanner
        run: echo 'Skipping this one'

      - name: Coverage Check
        run: echo 'Skipping this one'

      - name: Push
        run: npm run package

      - name: S3 Upload
        run: echo 's3 do something'

      - name: Hash
        run: echo 'Create S3 Hash file'
