name: Node JS CI
on:
  workflow_call:
    secrets:
      CVS_MGMT_AWS_ROLE:
        required: true
      CVS_SERVICES_S3:
        required: true
jobs:
  node-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: ${{ secrets.CVS_MGMT_AWS_ROLE }}
          aws-region: eu-west-1
          role-session-name: MGMTGHA

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Confirm Node and NPM versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Security Check
        run: echo 'Skipping for now'

      - name: Configure Tools
        run: npm run tools-setup

      - name: Run Linting
        run: npm run lint

      - name: Build
        run: npm run build
      
      - name: Run Tests
        run: npm run test

      - name: Run Integration Tests
        run: npm run test-i

      - name: Sonar Scanner
        run: echo 'Skipping this one'

      - name: Coverage Check
        run: echo 'Skipping this one'

      - name: Push
        env:
          ZIP_NAME: ${{ github.sha }}}
        run: |
          npm run package
          ls -la 
# openssl dgst -sha256 -binary ${{ github.sha }}.zip | openssl enc -base64
# repo=$(echo ${GITHUB_REPOSITORY#dvsa/cvs-})
# echo $repo

      # - name: S3 Upload
      #   run: aws s3 cp 

      # - name: Hash
      #   run: echo 'Create S3 Hash file'
