name: Receiver 
run-name: "${{github.event.action}} - ${{ github.event.client_payload.branch }}"
on:
  repository_dispatch:
    types: [create, build, delete]

jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: Received Event!
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "event '${{ github.event.action }}'"
          echo "payload branch '${{ github.event.client_payload.branch }}'"
          echo "payload source branch '${{ github.event.client_payload.source-branch }}'"

  create:
    if: github.event.action == 'create' || github.event.action == 'create & build'
    name: ✅ Create ${{  github.event.client_payload.branch }} from ${{  github.event.client_payload.source-branch }}
    uses: ./.github/workflows/branch-actioner.yaml
    with:
      action: 'create'
      branch: ${{ github.event.client_payload.branch }}
      source-branch: ${{ github.event.client_payload.source-branch }}

  build:
    if: github.event.action == 'build' || github.event.action == 'create & build'
    name: ✅ Create ${{  github.event.client_payload.branch }} from ${{  github.event.client_payload.source-branch }}
    uses: ./.github/workflows/branch-actioner.yaml
    with:
      action: 'build'
      branch: ${{ github.event.client_payload.branch }}
      source-branch: ${{ github.event.client_payload.source-branch }}

  delete:
    if: github.event.action == 'delete'
    name: ⛔️ Delete ${{ github.event.client_payload.branch }}
    uses: ./.github/workflows/branch-actioner.yaml
    with:
      action: 'delete'
      branch: ${{ github.event.client_payload.branch }}
      source-branch: ${{ github.event.client_payload.source-branch }}
