name: Receiver 
on:
  repository_dispatch:
    types: [create, build, delete]
jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: Received Event!
        run: |
          echo "event '${{ github.event_name }}'"
          echo "payload branch '${{ github.event.client_payload.branch }}'"
          echo "payload source branch '${{ github.event.client_payload.source-branch }}'"