name: Receiver 
on:
  repository_dispatch:
    types: [create, build, delete]
jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: Received Event!
        run: |
          echo "${{ github.event }}" | jq '.'
          echo "${{ github.event.client_payload }}" | jq '.'