name: Create Release Branch
run-name: "${{ github.actor }} - ${{ github.ref_name }} - ${{ github.run_id }} 🚀"

on:
  workflow_dispatch:
    inputs:
      source-branch: 
        type: string
        required: true      
      release-branch:
          type: string
          required: true
      dry-run:
        type: boolean
        default: true

jobs:
  test-release:
    name: Testing
    uses: ./.github/workflows/create-release.yaml
    with:
      release-branch-name: ${{ inputs.release-branch }}
      source-branch-name: ${{ inputs.source-branch }}
      dry-run: ${{ inputs.dry-run }}